name: CYBERX2002
favicon: null
layout_spectrum: 0.5292
typography_spectrum: 0.40248
title: Site Test 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37571647
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#404040'
    - '#c0c0c0'
    - '#858585'
  brandStrength: 0
  lightness: 0.4621971894521266
  saturation: 0.28532835957594216
  rhythmicContrast: 0.5206216394435614
purpose: []
